## Introduction to Pandas (Python Library)

#### install pandas

In [10]:
pip install pandas

Requirement already satisfied: pandas in c:\users\dilsh\anaconda3\lib\site-packages (2.1.4)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy<2,>=1.26.0 in c:\users\dilsh\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dilsh\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dilsh\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\dilsh\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\dilsh\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

pip → Python package installer

install → download & install

pandas → library name

👉 This command downloads Pandas and installs it in Python.

If Pandas is already installed,
it will show “Requirement already satisfied” ✅

pip install pandas → only once

import pandas as pd → every notebook

#### import pandas

In [13]:
import pandas as pd

#### Check Pandas Version (Optional)

In [19]:
pd.__version__

'2.1.4'

#### Create a Simple DataFrame

In [25]:
data={ 'Name':['naja','fidha','husna'],
      'age':[22,45,67]}

In [27]:
df=pd.DataFrame(data)
df

    Name  age
0   naja   22
1  fidha   45
2  husna   67

Dictionary → Data

DataFrame() → Table

Output looks like Excel

See, this table you are seeing is a DataFrame.
Each column is like a Series.
Pandas internally uses data structures & arrays.

                                            question

Install Pandas

Import Pandas

Create a DataFrame with:

Name

Age

City

## Create a Pandas Series

In [38]:
marks=pd.Series([65,76,45,87])
marks

0    65
1    76
2    45
3    87
dtype: int64

“Series is like a list plus index labels, plus analytics power.
List is general-purpose, Series is data-analysis-purpose.”

By default, Pandas gives index as 0, 1, 2

In [65]:
marks=pd.Series([45,67,87,98,45],index=['maths','english','social','hindi','malayala'])
marks

maths       45
english     67
social      87
hindi       98
malayala    45
dtype: int64

In [67]:
df=pd.DataFrame(marks)
df

           0
maths     45
english   67
social    87
hindi     98
malayala  45

In [73]:
marks['maths']

45

In [75]:
marks[0]

C:\Users\dilsh\AppData\Local\Temp\ipykernel_18792\1318454221.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  marks[0]

45

In [80]:
marks[3]

C:\Users\dilsh\AppData\Local\Temp\ipykernel_18792\2490810457.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  marks[3]

98

In [56]:
df=pd.DataFrame({'marks':[45,67,87,98,45],
                'sub':['maths','english','social','hindi','malayala']})
df

   marks       sub
0     45     maths
1     67   english
2     87    social
3     98     hindi
4     45  malayala

#### Series from Dictionary (Important)

In [83]:
student_mark={'math':23,'eng':65,'mala':78}

In [117]:
df=pd.Series(student_mark)
df

math    23
eng     65
mala    78
dtype: int64

In [89]:
a=pd.DataFrame(df)
a

       0
math  23
eng   65
mala  78

Dictionary keys → index

Dictionary values → data

#### Series Properties

In [119]:
df.index

Index(['math', 'eng', 'mala'], dtype='object')

In [121]:
df.values

array([23, 65, 78], dtype=int64)

In [123]:
df.dtypes

dtype('int64')

In [125]:
df.shape                  ####The size of the Series as a tuple

(3,)

In [127]:
len(df)

3

In [129]:
df.size

3

In [135]:
df.ndim                            #####  Number of dimensions


### 1 — because a Series is a one‑dimensional labeled array.
### 2-DataFrame Two‑dimensional (rows × columns)

1

In [137]:
df.hasnans                  ### check is there any NaN values

False

 NaN and NULL both represent missing or blank values in pandas.

In [139]:
df.is_unique

True

checks whether the Series has duplicates
- True → all values are unique
- False → duplicates exist

In [141]:
df.sort_values()                                       #### Ascending order

math    23
eng     65
mala    78
dtype: int64

In [145]:
df.sort_values(ascending=False)                        ##### DESC

mala    78
eng     65
math    23
dtype: int64

In [147]:
df.sort_index()                                 ### sort index

eng     65
mala    78
math    23
dtype: int64

### Create a DataFrame (Core Concept)

In [203]:
df=pd.DataFrame({'name':['naja','fidha','ram','rahul'],
                 'age':[22,45,34,25]})
df

    name  age
0   naja   22
1  fidha   45
2    ram   34
3  rahul   25

## Understand DataFrame Structure

In [155]:
df.shape

(4, 2)

In [157]:
df.columns

Index(['name', 'age'], dtype='object')

In [159]:
df.index

RangeIndex(start=0, stop=4, step=1)

### DataFrame Information

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

Explain:

     Column name

     Data type

     Non-null values

In [168]:
df.describe()

            age
count   4.00000
mean   31.50000
std    10.34408
min    22.00000
25%    24.25000
50%    29.50000
75%    36.75000
max    45.00000

Explain:

      count

      mean
 
    min / max
(Only numeric columns)

### Select Data from DataFrame

In [173]:
df['age']

0    22
1    45
2    34
3    25
Name: age, dtype: int64

### Select Multiple Columns (DataFrame output)

In [182]:
df[['name','age']]

    name  age
0   naja   22
1  fidha   45
2    ram   34
3  rahul   25

### Select Rows

In [207]:
df.loc[1]                 ### return the first row

name    fidha
age        45
Name: 1, dtype: object

In [191]:
df.iloc[0]

name    naja
age       22
Name: 0, dtype: object

In [195]:
df.loc[1:3]

    name  age
1  fidha   45
2    ram   34
3  rahul   25

#### if we want a column

In [212]:
df.loc[:,'age']

0    22
1    45
2    34
3    25
Name: age, dtype: int64

In [ ]:
In pandas, the colon means “select everything in this dimension.”
So in:


- The first position (before the comma) is for rows
- The second position (after the comma) is for columns
Thus:
- : → all rows
- 'age' → only the age column
So the line means:
“Select all rows, but only the age column.”

In [218]:
df.loc[0:2,'name']

0     naja
1    fidha
2      ram
Name: name, dtype: object

loc → label

iloc → index position

Each column here is a Series.
Series works like an array.
DataFrame is a data structure made using Series.”

Q) Ask students to create a DataFrame with:

Student_Name

Subject

Marks

1)Then ask them to:

2)Show only Marks column

3)Show first row

4)Check shape

# DAY 3

Yesterday we created Series and DataFrame manually.
But in real life, we don’t type data.
Today we will LOAD data from files like CSV and Excel

What is a CSV File? (Before Code)
Explain:

CSV = Comma Separated Values

Most common file used in data analytics

Lightweight and fast

Example CSV structure:

Name,Age,Marks
Ali,20,85
Sara,21,90
John,19,78